service: comments-helper-bot

provider:
  name: aws
  runtime: python3.8
  memorySize: 256
  lambdaHashingVersion: 20201221
  environment:
    TOKEN: ${file(./serverless.env.yml):TOKEN, ''}
    REDIS_HOST: ${file(./serverless.env.yml):REDIS_HOST, ''}
    REDIS_PORT: ${file(./serverless.env.yml):REDIS_PORT, ''}
    REDIS_PASSWORD: ${file(./serverless.env.yml):REDIS_PASSWORD, ''}

functions:
  webhook:
    handler: lambda_handler.webhook
    events:
      - httpApi: POST /${file(./serverless.env.yml):TOKEN, ''}

  set_webhook:
    handler: lambda_handler.set_webhook
    events:
      - httpApi: POST /set_webhook
      - httpApi: GET /set_webhook

package:
  patterns:
    - '!.idea/**'
    - '!.vercel/**'
    - '!api/**'
    - '!__pycache__/**'
    - '!README.md'
    - '!LICENSE'
    - '!Dockerfile'
    - '!serverless.env.yml'
    - '!main.py'

plugins:
  - serverless-python-requirements
